cloud:
  aws:
    credentials:
      access-key: sadsad
      secret-key: sdsad
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: videosphim
  cloudfront:
    url: https://d2g4rgl51ql2fk.cloudfront.net

spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 500MB
      max-file-size: 500MB

server:
  port: 9090
